AHCI_RUNTIME_PM_ON_AC=on
AHCI_RUNTIME_PM_ON_BAT=on
AHCI_RUNTIME_PM_TIMEOUT=0
AMDGPU_ABM_LEVEL_ON_AC=0
AMDGPU_ABM_LEVEL_ON_BAT=0
AMDGPU_ABM_LEVEL_ON_SAV=0
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=1
CPU_BOOST_ON_SAV=1
CPU_DRIVER_OPMODE_ON_AC=active
CPU_DRIVER_OPMODE_ON_BAT=active
CPU_DRIVER_OPMODE_ON_SAV=active
CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_BAT=performance
CPU_ENERGY_PERF_POLICY_ON_SAV=performance
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=performance
CPU_SCALING_GOVERNOR_ON_SAV=performance
CPU_SCALING_MAX_FREQ_ON_AC=4954565
CPU_SCALING_MAX_FREQ_ON_BAT=4954565
CPU_SCALING_MAX_FREQ_ON_SAV=4954565
CPU_SCALING_MIN_FREQ_ON_AC=4954565
CPU_SCALING_MIN_FREQ_ON_BAT=4954565
CPU_SCALING_MIN_FREQ_ON_SAV=4954565
DISK_APM_CLASS_DENYLIST=usb
DISK_APM_LEVEL_ON_AC=255 255
DISK_DEVICES=sda sdb
DISK_IDLE_SECS_ON_AC=0
DISK_IDLE_SECS_ON_BAT=0
DISK_IOSCHED=kyber kyber
DISK_SPINDOWN_TIMEOUT_ON_AC=0 0
DISK_SPINDOWN_TIMEOUT_ON_BAT=0 0
MAX_LOST_WORK_SECS_ON_AC=5
MAX_LOST_WORK_SECS_ON_BAT=5
PCIE_ASPM_ON_AC=performance
PCIE_ASPM_ON_BAT=performance
PLATFORM_PROFILE_ON_AC=performance
PLATFORM_PROFILE_ON_BAT=performance
PLATFORM_PROFILE_ON_SAV=performance
RADEON_DPM_PERF_LEVEL_ON_AC=high
RADEON_DPM_PERF_LEVEL_ON_BAT=high
RADEON_DPM_STATE_ON_AC=performance
RADEON_DPM_STATE_ON_BAT=performance
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=on
SATA_LINKPWR_ON_AC=max_performance
SATA_LINKPWR_ON_BAT=max_performance
SOUND_POWER_SAVE_CONTROLLER=N
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=0
USB_AUTOSUSPEND=0
